// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contact struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Name      string  `json:"name"`
	Email     *string `json:"email"`
	Phone     *string `json:"phone"`
	Notes     *string `json:"notes"`
	Active    bool    `json:"active"`
	CreatedBy string  `json:"created_by"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt string  `json:"deleted_at"`
}

type ContactDetail struct {
	ID        string          `json:"id"`
	Type      string          `json:"type"`
	Name      string          `json:"name"`
	Email     *string         `json:"email"`
	Phone     *string         `json:"phone"`
	Notes     *string         `json:"notes"`
	Active    bool            `json:"active"`
	CreatedBy []*UserOverview `json:"created_by"`
	CreatedAt string          `json:"created_at"`
	UpdatedAt string          `json:"updated_at"`
	DeletedAt string          `json:"deleted_at"`
}

type ContactOverview struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

type Event struct {
	ID                      string    `json:"id"`
	EventLead               string    `json:"event_lead"`
	CoPlanners              []*string `json:"co_planners"`
	Title                   string    `json:"title"`
	Description             string    `json:"description"`
	StartDate               string    `json:"start_date"`
	SetUp                   string    `json:"set_up"`
	CleanUp                 string    `json:"clean_up"`
	EndDate                 string    `json:"end_date"`
	GrantID                 string    `json:"grant_id"`
	PublicEvent             bool      `json:"public_event"`
	RsvpRequired            bool      `json:"rsvp_required"`
	AnnualEvent             bool      `json:"annual_event"`
	NewEvent                bool      `json:"new_event"`
	VolunteersNeeded        bool      `json:"volunteers_needed"`
	Agenda                  []string  `json:"agenda"`
	TargetAudience          string    `json:"target_audience"`
	PartingGifts            []*string `json:"parting_gifts"`
	MarketingMaterial       []*string `json:"marketing_material"`
	Supplies                []*string `json:"supplies"`
	SpecialOrders           []*string `json:"special_orders"`
	Performance             string    `json:"performance"`
	Vendors                 string    `json:"vendors"`
	FoodAndBeverage         []*string `json:"food_and_beverage"`
	Caterer                 string    `json:"caterer"`
	FoodHeadCount           int       `json:"food_head_count"`
	EventTeam               []*string `json:"event_team"`
	VolunteerList           []*string `json:"volunteer_list"`
	Budget                  float64   `json:"budget"`
	AffiliatedOrganizations []*string `json:"affiliated_organizations"`
	EducationalGoals        []string  `json:"educational_goals"`
	EducationalOutcomes     []string  `json:"educational_outcomes"`
	GrantGoals              []string  `json:"grant_goals"`
	CreatedAt               string    `json:"created_at"`
	UpdatedAt               string    `json:"updated_at"`
	Status                  string    `json:"status"`
}

type EventDescription struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	StartDate string `json:"start_date"`
}

type EventOverview struct {
	ID        string          `json:"id"`
	EventLead []*UserOverview `json:"event_lead"`
	Title     string          `json:"title"`
	StartDate string          `json:"start_date"`
	CreatedAt string          `json:"created_at"`
	Status    string          `json:"status"`
	NoteCount int             `json:"note_count"`
}

type EventRes struct {
	ID        string        `json:"id"`
	EventLead *UserOverview `json:"event_lead"`
	Title     string        `json:"title"`
	StartDate string        `json:"start_date"`
	Status    string        `json:"status"`
	CreatedAt string        `json:"created_at"`
}

type EventSummary struct {
	ID            string    `json:"id"`
	EventID       string    `json:"event_id"`
	UserID        string    `json:"user_id"`
	CoPlanners    []*string `json:"co_planners"`
	AttendeeCount int       `json:"attendee_count"`
	Challenges    string    `json:"challenges"`
	Successes     string    `json:"successes"`
	Improvements  string    `json:"improvements"`
	Status        string    `json:"status"`
	CreatedAt     string    `json:"created_at"`
	UpdatedAt     string    `json:"updated_at"`
}

type EventSummaryOverview struct {
	ID               string              `json:"id"`
	EventDescription []*EventDescription `json:"event_description"`
	SummaryAuthor    []*UserOverview     `json:"summary_author"`
	AttendeeCount    int                 `json:"attendee_count"`
	Status           string              `json:"status"`
	CreatedAt        string              `json:"created_at"`
	NoteCount        int                 `json:"note_count"`
}

type EventSummaryRes struct {
	ID            string            `json:"id"`
	Event         *EventDescription `json:"event"`
	SummaryAuthor *UserOverview     `json:"summary_author"`
	Status        string            `json:"status"`
	CreatedAt     string            `json:"created_at"`
}

type EventSummaryWithNotes struct {
	ID               string              `json:"id"`
	EventDescription []*EventDescription `json:"event_description"`
	SummaryAuthor    []*UserOverview     `json:"summary_author"`
	CoPlanners       []*UserOverview     `json:"co_planners"`
	AttendeeCount    int                 `json:"attendee_count"`
	Challenges       string              `json:"challenges"`
	Successes        string              `json:"successes"`
	Improvements     string              `json:"improvements"`
	Status           string              `json:"status"`
	CreatedAt        string              `json:"created_at"`
	UpdatedAt        string              `json:"updated_at"`
	Notes            []*Note             `json:"notes"`
}

type EventWithNotes struct {
	ID                      string          `json:"id"`
	EventLead               []*UserOverview `json:"event_lead"`
	CoPlanners              []*UserOverview `json:"co_planners"`
	Title                   string          `json:"title"`
	Description             string          `json:"description"`
	StartDate               string          `json:"start_date"`
	SetUp                   string          `json:"set_up"`
	CleanUp                 string          `json:"clean_up"`
	EndDate                 string          `json:"end_date"`
	GrantID                 string          `json:"grant_id"`
	PublicEvent             bool            `json:"public_event"`
	RsvpRequired            bool            `json:"rsvp_required"`
	AnnualEvent             bool            `json:"annual_event"`
	NewEvent                bool            `json:"new_event"`
	VolunteersNeeded        bool            `json:"volunteers_needed"`
	Agenda                  []string        `json:"agenda"`
	TargetAudience          string          `json:"target_audience"`
	PartingGifts            []*string       `json:"parting_gifts"`
	MarketingMaterial       []*string       `json:"marketing_material"`
	Supplies                []*string       `json:"supplies"`
	SpecialOrders           []*string       `json:"special_orders"`
	Performance             string          `json:"performance"`
	Vendors                 string          `json:"vendors"`
	FoodAndBeverage         []*string       `json:"food_and_beverage"`
	Caterer                 string          `json:"caterer"`
	FoodHeadCount           int             `json:"food_head_count"`
	EventTeam               []*string       `json:"event_team"`
	VolunteerList           []*string       `json:"volunteer_list"`
	Budget                  float64         `json:"budget"`
	AffiliatedOrganizations []*string       `json:"affiliated_organizations"`
	EducationalGoals        []string        `json:"educational_goals"`
	EducationalOutcomes     []string        `json:"educational_outcomes"`
	GrantGoals              []string        `json:"grant_goals"`
	CreatedAt               string          `json:"created_at"`
	UpdatedAt               string          `json:"updated_at"`
	Status                  string          `json:"status"`
	Notes                   []*Note         `json:"notes"`
}

type Grant struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Goals       []string `json:"goals"`
	Objectives  []string `json:"objectives"`
	StartDate   string   `json:"start_date"`
	AwardDate   string   `json:"award_date"`
	EndDate     string   `json:"end_date"`
	AwardNumber string   `json:"award_number"`
	Budget      float64  `json:"budget"`
	Active      bool     `json:"active"`
	CreatedBy   string   `json:"created_by"`
	CreatedAt   string   `json:"created_at"`
	UpdatedAt   string   `json:"updated_at"`
}

type GrantDetail struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Goals       []string        `json:"goals"`
	Objectives  []string        `json:"objectives"`
	StartDate   string          `json:"start_date"`
	AwardDate   string          `json:"award_date"`
	EndDate     string          `json:"end_date"`
	AwardNumber string          `json:"award_number"`
	Budget      float64         `json:"budget"`
	Active      bool            `json:"active"`
	CreatedBy   []*UserOverview `json:"created_by"`
	CreatedAt   string          `json:"created_at"`
	UpdatedAt   string          `json:"updated_at"`
}

type GrantOverview struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	StartDate   string  `json:"start_date"`
	AwardDate   string  `json:"award_date"`
	EndDate     string  `json:"end_date"`
	AwardNumber string  `json:"award_number"`
	Budget      float64 `json:"budget"`
	Active      bool    `json:"active"`
}

type ItemOverview struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

type Log struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	DailyActivity string `json:"daily_activity"`
	Positives     string `json:"positives"`
	Improvements  string `json:"improvements"`
	NextSteps     string `json:"next_steps"`
	Status        string `json:"status"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type LogOverview struct {
	ID        string          `json:"id"`
	LogAuthor []*UserOverview `json:"log_author"`
	CreatedAt string          `json:"created_at"`
	UpdatedAt string          `json:"updated_at"`
	Status    string          `json:"status"`
	NoteCount int             `json:"note_count"`
}

type LogRes struct {
	ID        string        `json:"id"`
	LogAuthor *UserOverview `json:"log_author"`
	Status    string        `json:"status"`
	CreatedAt string        `json:"created_at"`
}

type LogWithNotes struct {
	ID            string          `json:"id"`
	LogAuthor     []*UserOverview `json:"log_author"`
	DailyActivity string          `json:"daily_activity"`
	Positives     string          `json:"positives"`
	Improvements  string          `json:"improvements"`
	NextSteps     string          `json:"next_steps"`
	Status        string          `json:"status"`
	CreatedAt     string          `json:"created_at"`
	UpdatedAt     string          `json:"updated_at"`
	Notes         []*Note         `json:"notes"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRes struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Active    bool   `json:"active"`
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
}

type NewContact struct {
	Name  string  `json:"name"`
	Type  string  `json:"type"`
	Email *string `json:"email"`
	Phone *string `json:"phone"`
	Notes *string `json:"notes"`
}

type NewEvent struct {
	CoPlanners              []*string `json:"co_planners"`
	Title                   string    `json:"title"`
	Description             string    `json:"description"`
	StartDate               string    `json:"start_date"`
	SetUp                   string    `json:"set_up"`
	CleanUp                 string    `json:"clean_up"`
	EndDate                 string    `json:"end_date"`
	GrantID                 string    `json:"grant_id"`
	PublicEvent             bool      `json:"public_event"`
	RsvpRequired            bool      `json:"rsvp_required"`
	AnnualEvent             bool      `json:"annual_event"`
	NewEvent                bool      `json:"new_event"`
	VolunteersNeeded        bool      `json:"volunteers_needed"`
	Agenda                  []string  `json:"agenda"`
	TargetAudience          string    `json:"target_audience"`
	PartingGifts            []*string `json:"parting_gifts"`
	MarketingMaterials      []*string `json:"marketing_materials"`
	Supplies                []*string `json:"supplies"`
	SpecialOrders           []*string `json:"special_orders"`
	Performance             *string   `json:"performance"`
	Vendors                 *string   `json:"vendors"`
	FoodAndBeverage         []*string `json:"food_and_beverage"`
	Caterer                 *string   `json:"caterer"`
	FoodHeadCount           int       `json:"food_head_count"`
	EventTeam               []*string `json:"event_team"`
	VolunteerList           []*string `json:"volunteer_list"`
	Budget                  float64   `json:"budget"`
	AffiliatedOrganizations []*string `json:"affiliated_organizations"`
	EducationalGoals        []string  `json:"educational_goals"`
	EducationalOutcomes     []string  `json:"educational_outcomes"`
	GrantGoals              []string  `json:"grant_goals"`
}

type NewEventSummary struct {
	EventID       string    `json:"event_id"`
	CoPlanners    []*string `json:"co_planners"`
	AttendeeCount int       `json:"attendee_count"`
	Challenges    string    `json:"challenges"`
	Successes     string    `json:"successes"`
	Improvements  string    `json:"improvements"`
}

type NewGrant struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Goals       []string `json:"goals"`
	Objectives  []string `json:"objectives"`
	StartDate   string   `json:"start_date"`
	EndDate     string   `json:"end_date"`
	Budget      float64  `json:"budget"`
	AwardNumber string   `json:"award_number"`
	AwardDate   string   `json:"award_date"`
}

type NewLog struct {
	DailyActivity string `json:"daily_activity"`
	Positives     string `json:"positives"`
	Improvements  string `json:"improvements"`
	NextSteps     string `json:"next_steps"`
}

type NewNote struct {
	ItemID  string `json:"item_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewSchoolReportDebrief struct {
	LessonPlanID           string   `json:"lesson_plan_id"`
	StudentCount           int      `json:"student_count"`
	StudentList            []string `json:"student_list"`
	ChallengesImprovements string   `json:"challenges_improvements"`
	Positives              string   `json:"positives"`
	Discussion             string   `json:"discussion"`
}

type NewSchoolReportPlan struct {
	CoFacilitators []*string `json:"co_facilitators"`
	Curriculum     string    `json:"curriculum"`
	School         string    `json:"school"`
	LessonTopics   string    `json:"lesson_topics"`
}

type NewUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type Note struct {
	ID        string `json:"id"`
	ItemID    string `json:"item_id"`
	UserID    string `json:"user_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type NoteDetail struct {
	ID        string        `json:"id"`
	ItemInfo  *ItemOverview `json:"item_info"`
	Author    *UserOverview `json:"author"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	CreatedAt string        `json:"created_at"`
	UpdatedAt string        `json:"updated_at"`
}

type SchoolReportDebrief struct {
	ID                     string   `json:"id"`
	UserID                 string   `json:"user_id"`
	LessonPlanID           string   `json:"lesson_plan_id"`
	StudentCount           int      `json:"student_count"`
	StudentList            []string `json:"student_list"`
	ChallengesImprovements string   `json:"challenges_improvements"`
	Positives              string   `json:"positives"`
	Discussion             string   `json:"discussion"`
	Status                 string   `json:"status"`
	CreatedAt              string   `json:"created_at"`
	UpdatedAt              string   `json:"updated_at"`
}

type SchoolReportDebriefOverview struct {
	ID            string                         `json:"id"`
	DebriefAuthor []*UserOverview                `json:"debrief_author"`
	LessonPlan    []*SchoolReportPlanDescription `json:"lesson_plan"`
	Status        string                         `json:"status"`
	CreatedAt     string                         `json:"created_at"`
	NoteCount     int                            `json:"note_count"`
}

type SchoolReportDebriefRes struct {
	ID            string                       `json:"id"`
	DebriefAuthor *UserOverview                `json:"debrief_author"`
	LessonPlan    *SchoolReportPlanDescription `json:"lesson_plan"`
	Status        string                       `json:"status"`
	CreatedAt     string                       `json:"created_at"`
}

type SchoolReportDebriefWithNotes struct {
	ID                     string                         `json:"id"`
	DebriefAuthor          []*UserOverview                `json:"debrief_author"`
	LessonPlan             []*SchoolReportPlanDescription `json:"lesson_plan"`
	StudentCount           int                            `json:"student_count"`
	StudentList            []string                       `json:"student_list"`
	ChallengesImprovements string                         `json:"challenges_improvements"`
	Positives              string                         `json:"positives"`
	Discussion             string                         `json:"discussion"`
	Status                 string                         `json:"status"`
	CreatedAt              string                         `json:"created_at"`
	UpdatedAt              string                         `json:"updated_at"`
	Notes                  []*Note                        `json:"notes"`
}

type SchoolReportPlan struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Date           string    `json:"date"`
	CoFacilitators []*string `json:"co_facilitators"`
	Curriculum     string    `json:"curriculum"`
	School         string    `json:"school"`
	LessonTopics   string    `json:"lesson_topics"`
	Status         string    `json:"status"`
	CreatedAt      string    `json:"created_at"`
	UpdatedAt      string    `json:"updated_at"`
}

type SchoolReportPlanDescription struct {
	ID     string `json:"id"`
	School string `json:"school"`
	Date   string `json:"date"`
}

type SchoolReportPlanOverview struct {
	ID           string          `json:"id"`
	Date         string          `json:"date"`
	ReportAuthor []*UserOverview `json:"report_author"`
	School       string          `json:"school"`
	Status       string          `json:"status"`
	CreatedAt    string          `json:"created_at"`
	NoteCount    int             `json:"note_count"`
}

type SchoolReportPlanRes struct {
	ID         string        `json:"id"`
	PlanAuthor *UserOverview `json:"plan_author"`
	Date       string        `json:"date"`
	School     string        `json:"school"`
	Status     string        `json:"status"`
	CreatedAt  string        `json:"created_at"`
}

type SchoolReportPlanWithNotes struct {
	ID             string          `json:"id"`
	Date           string          `json:"date"`
	ReportAuthor   []*UserOverview `json:"report_author"`
	CoFacilitators []*UserOverview `json:"co_facilitators"`
	Curriculum     string          `json:"curriculum"`
	School         string          `json:"school"`
	LessonTopics   string          `json:"lesson_topics"`
	Status         string          `json:"status"`
	CreatedAt      string          `json:"created_at"`
	UpdatedAt      string          `json:"updated_at"`
}

type UpdateContact struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Type  string  `json:"type"`
	Email *string `json:"email"`
	Phone *string `json:"phone"`
	Notes *string `json:"notes"`
}

type UpdateEvent struct {
	ID                      string    `json:"id"`
	CoPlanners              []*string `json:"co_planners"`
	Title                   string    `json:"title"`
	Description             string    `json:"description"`
	StartDate               string    `json:"start_date"`
	SetUp                   string    `json:"set_up"`
	CleanUp                 string    `json:"clean_up"`
	EndDate                 string    `json:"end_date"`
	GrantID                 string    `json:"grant_id"`
	PublicEvent             bool      `json:"public_event"`
	RsvpRequired            bool      `json:"rsvp_required"`
	AnnualEvent             bool      `json:"annual_event"`
	NewEvent                bool      `json:"new_event"`
	VolunteersNeeded        bool      `json:"volunteers_needed"`
	Agenda                  []string  `json:"agenda"`
	TargetAudience          string    `json:"target_audience"`
	PartingGifts            []*string `json:"parting_gifts"`
	MarketingMaterials      []*string `json:"marketing_materials"`
	Supplies                []*string `json:"supplies"`
	SpecialOrders           []*string `json:"special_orders"`
	Performance             *string   `json:"performance"`
	Vendors                 *string   `json:"vendors"`
	FoodAndBeverage         []*string `json:"food_and_beverage"`
	Caterer                 *string   `json:"caterer"`
	FoodHeadCount           int       `json:"food_head_count"`
	EventTeam               []*string `json:"event_team"`
	VolunteerList           []*string `json:"volunteer_list"`
	Budget                  float64   `json:"budget"`
	AffiliatedOrganizations []*string `json:"affiliated_organizations"`
	EducationalGoals        []string  `json:"educational_goals"`
	EducationalOutcomes     []string  `json:"educational_outcomes"`
	GrantGoals              []string  `json:"grant_goals"`
}

type UpdateEventSummary struct {
	ID            string    `json:"id"`
	EventID       string    `json:"event_id"`
	CoPlanners    []*string `json:"co_planners"`
	AttendeeCount int       `json:"attendee_count"`
	Challenges    string    `json:"challenges"`
	Successes     string    `json:"successes"`
	Improvements  string    `json:"improvements"`
	Status        string    `json:"status"`
}

type UpdateGrant struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Goals       []string `json:"goals"`
	Objectives  []string `json:"objectives"`
	StartDate   string   `json:"start_date"`
	EndDate     string   `json:"end_date"`
	Budget      float64  `json:"budget"`
	AwardNumber string   `json:"award_number"`
	AwardDate   string   `json:"award_date"`
	Active      bool     `json:"active"`
}

type UpdateLog struct {
	ID            string `json:"id"`
	DailyActivity string `json:"daily_activity"`
	Positives     string `json:"positives"`
	Improvements  string `json:"improvements"`
	NextSteps     string `json:"next_steps"`
	Status        string `json:"status"`
}

type UpdateNote struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdateSchoolReportDebrief struct {
	ID                     string   `json:"id"`
	LessonPlanID           string   `json:"lesson_plan_id"`
	StudentCount           int      `json:"student_count"`
	StudentList            []string `json:"student_list"`
	ChallengesImprovements string   `json:"challenges_improvements"`
	Positives              string   `json:"positives"`
	Discussion             string   `json:"discussion"`
	Status                 string   `json:"status"`
}

type UpdateSchoolReportPlan struct {
	ID             string    `json:"id"`
	CoFacilitators []*string `json:"co_facilitators"`
	Curriculum     string    `json:"curriculum"`
	LessonTopics   string    `json:"lesson_topics"`
	School         string    `json:"school"`
	Status         string    `json:"status"`
}

type UpdateUser struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Admin     bool   `json:"admin"`
	Active    bool   `json:"active"`
}

type User struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Admin     bool    `json:"admin"`
	Active    bool    `json:"active"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type UserOverview struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type UserUpdateRes struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Admin     bool   `json:"admin"`
	Active    bool   `json:"active"`
	UpdatedAt string `json:"updated_at"`
}
