// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Log struct {
	ID        *string `json:"id"`
	UserID    *string `json:"user_id"`
	Action    string  `json:"action"`
	CreatedAt string  `json:"created_at"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewLog struct {
	Action string `json:"action"`
}

type NewUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID        *string `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	IsAdmin   bool    `json:"is_admin"`
}
