// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Log struct {
	ID           *string `json:"id"`
	UserID       *string `json:"user_id"`
	FocusArea    string  `json:"focus_area"`
	Actions      string  `json:"actions"`
	Successes    string  `json:"successes"`
	Improvements string  `json:"improvements"`
	NextSteps    string  `json:"next_steps"`
	Status       string  `json:"status"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewLog struct {
	FocusArea    string `json:"focus_area"`
	Actions      string `json:"actions"`
	Successes    string `json:"successes"`
	Improvements string `json:"improvements"`
	NextSteps    string `json:"next_steps"`
}

type NewUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateLog struct {
	FocusArea    string `json:"focus_area"`
	Actions      string `json:"actions"`
	Successes    string `json:"successes"`
	Improvements string `json:"improvements"`
	NextSteps    string `json:"next_steps"`
	Status       string `json:"status"`
}

type User struct {
	ID        *string `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	IsAdmin   bool    `json:"is_admin"`
}
