name: Docker Image CI
on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:

    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Configure Google Cloud Authentication'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/742353511535/locations/global/workloadIdentityPools/nora/providers/github-action'
        service_account: 'thomps9012@counselorproductivity.iam.gserviceaccount.com'

    - id: 'gcloud'
      name: 'gCloud Service List'
      run: |-
        gcloud auth login --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list --project='counselorproductivity'
    
    - name: 'Configures Gcloud Docker'
      run: gcloud auth configure-docker
    
    - name: 'Lists Images in Gcloud'
      run: gcloud container images list-tags gcr.io/counselorproductivity/prevention-api

    - name: 'Build the Docker Image'
      run: docker build -t prevention-api .

    - name: 'Tags the Docker Image for the Google Container Registry'
      run: docker tag prevention-api gcr.io/counselorproductivity/prevention-api

    - name: 'Pushes the Docker Image to the Google Container Registry'
      run: docker push gcr.io/counselorproductivity/prevention-api